alias: keck
name: Keck Telescope
effects:
  - name: primary_mirror
    class: SurfaceList
    kwargs:
      aperture: 10  # meters
      focal_length: 17.5  # meters
    meta:
      type: telescope
      image_plane_id: 0