[build-system]
# Specifies the build system to use. 
requires = ["setuptools>=42", "cython"]
build-backend = "setuptools.build_meta"

[project]
# Basic information about your project.
name = "zs-scopesim" 
version = "0.1.0" 
dependencies = [
  "matplotlib",
  "astropy",
  "numpy",
  "cython",
  "scopesim @ git+https://github.com/CaltechOpticalObservatories/ScopeSim.git@main",
  "irdb @ git+https://github.com/CaltechOpticalObservatories/irdb.git@dev_master",
  "scopesim_templates",
]
requires-python = ">=3.10, <3.15"
authors = [
  {name = "Yashvi Sharma", email = "yssharma@astro.caltech.edu"}
]
maintainers = [
  {name = "Yashvi Sharma", email = "yssharma@astro.caltech.edu"}
]
description = "Simulator for ZShooter using ScopSim framework"
readme = "README.md" 
license = { text = "GNU GPLv3" }
keywords = ["astronomy"]
classifiers = [
  "Programming Language :: Python"
]

[tool.setuptools.packages.find]
where = ["PALACE"]

[tool.setuptools.package-data]
"palace.data" = ["*.fits"]
"palace.config" = ["*.par"]

[project.urls]
# Various URLs related to your project. These links are displayed on PyPI.
Repository = "https://github.com/CaltechOpticalObservatories/zs-scopesim"
"Bug Tracker" = "https://github.com/CaltechOpticalObservatories/zs-scopesim/issues" 
Changelog = "https://github.com/CaltechOpticalObservatories/zs-scopesim/blob/master/CHANGELOG.md"


[project.optional-dependencies]
# Optional dependencies that can be installed with extra tags, like "dev".
dev = [
  "pytest", 
  "black",
  "flake8"
]
