---
### default observation parameters needed for ZShooter simulation

object: configuration
alias: OBS
name: ZShooter_default_configuration
description: default config for zshooter sim
status: development
version: 0.1

packages:
- MaunaKea
- keck
- ZShooter

yamls:
- MaunaKea.yaml
- keck.yaml
- ZShooter.yaml
- ZShooter_DET.yaml

properties:
  instrument : ZShooter
  modes : ["SPEC"]
  airmass : 1.2
  declination : 0
  hour_angle : 0
  pupil_angle : 0
  dit : 10
  ndit : 1
  mjdobs : 60920
  object : "Test"
  ra : 0.0
  dec : 0.0

mode_yamls:
- object: instrument
  alias: OBS
  name : SPEC
  description : "spectroscopic mode"
  yamls :
    - ZShooter_SPEC.yaml

---
### default simulation parameters needed for a MICADO simulation
object : simulation
alias : SIM
name : ZShooter_simulation_paramters
description : RC simulation paramters which need to change for a zshooter run

properties :
  random :
    seed : 9001

  spectral :
    wave_min : 0.3 #change
    wave_mid : 1.0 #change
    wave_max : 2.6 #change
    spectral_bin_width: 0.0005       # 0.5 Angstrom

  computing :
    preload_field_of_views : True

#  reports:
#    preamble_file: "../docs/.rst"
